### ISSUE TITLE
Config help

### ISSUE THREAD

**Issue by Johan8012** [F4stFr3ddy/homebridge-somfy-hotwired#10]
Sorry to ask.
I soldered. And installed the plugin. Im on HOOBS.
When I copy paste your Config sample down on the first page to my hoobs config.
Hoobs says cannot save, invalid JSON.

What am I doing wrong?

**Comment by F4stFr3ddy** [comment]
Can you give a full copy of your config with sensitive information redacted?

**Comment by Johan8012** [comment]
Sorry to disturb you. I use hoobs. Installed the plugin. And added your example config to accsessories [] i have soldererd the wires according to the pictures on the remote and inserted the wires on the rasperry pi 3 5 and 7 places.
I see the switch on hoobs and on homekit.
Nothing happens when i press the switch. If i press the buttons on the remote it works.
What am I missing?
Is there something more i should install? The depencies file? How?

**Comment by F4stFr3ddy** [comment]
Ok, so your invalid JSON error is now gone?

How does the remote get power? Only via battery?
