### ISSUE TITLE
Somfy Telis 4

### ISSUE THREAD

**Issue by dulle226** [F4stFr3ddy/homebridge-somfy-hotwired#3]
Hello, 

i have a question to this Topic. I d like to Use the Plugin with an telis4 Rts Remote. In your Description and configuration it Seems only a teils 1 can be integrated. How can i Use the 5 channel Rts Remote?

adding the Channel Switch on to an io pin of the py is clear, but How to do the config file. 

Can you help in this case?

**Comment by F4stFr3ddy** [comment]
Hi,

I do not have the Telis4 Remote so I am unavailable to verify how it works. 

However it seems as simple as adding 1 wire and pressing it a few times. The problem however is controlling its state, e.g. after a reboot we need to sync the software with the actual remote. I'm not sure how we could do that easily.

I found an interesting repo:
https://github.com/reitermarkus/somfy

Which seems to implement some measuring of the LED to determine which channel is selected.

Would you be able to help?
