### ISSUE TITLE
More pictures of the soldering

### ISSUE THREAD

**Issue by Johan8012** [F4stFr3ddy/homebridge-somfy-hotwired#4]
Hello!
Could you please explain the soldering in more detail or post more pictures.

**Comment by F4stFr3ddy** [comment]
Hi,

Yes I will post a few more pictures in a week or two as I need to migrate mine to a new setup.

**Comment by Johan8012** [comment]
Thank you! Nice setup!

Best regards, Johan Svahn

**Comment by Johan8012** [comment]
I just started the project and noticed that the board differs from yours. Can give hints where to solder?
![image](https://user-images.githubusercontent.com/77528955/111061170-a9064800-84aa-11eb-9d36-10992c4afb4a.jpg)

**Comment by Johan8012** [comment]
Other side. Battery removed!
![image](https://user-images.githubusercontent.com/77528955/111061197-c0ddcc00-84aa-11eb-88ac-c51e6d595356.jpg)

**Comment by F4stFr3ddy** [comment]
What type remote is this? I do not recognize 2 buttons. 

Regarding the soldering, the buttons should be similar. The power I'm not sure, you could leave the battery in and not connect power.
